### PR TITLE
Reorganizing the files

### PR DESCRIPTION
**Pull request by noahmanger**
This reorganizes the main FEC repo in order to combine all research-related tasks under a single `research` folder and move the `release_notes.md` file to the top level. This makes it cleaner and clearer to folks unfamiliar with the project.

image

What do you think @nickykrause ?

### CODE REVIEW

**Comment by nickykrause** [comment]
Sounds good to me. I noticed this moves the consent form, though, which I've linked users to in an email today, in preparation for testing this week. I assume this will break that link?

**Comment by noahmanger** [comment]
Oh yeah it will. We can wait to merge though.

**Comment by nickykrause** [comment]
Okay, cool - if we could wait to merge until midday Thursday, that'd be good (i.e., noon eastern or so)

**Comment by noahmanger** [comment]
@nickykrause think this is ok to merge now?

**Comment by nickykrause** [comment]
@noahmanger sure

**Pull request merged**
